# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- release/*
- production/*
pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # pipeline conditions
  isMain:       ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  isRelease:    ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/release') }}
  isProduction: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/production') }}
  
  # build information
  ACR.Name: 'projectdemo'
  ACR.ImageName: '$(ACR.Name):$(Build.BuildId)'
  ACR.FullName: '$(ACR.Name).azurecr.io'

stages:
- stage: Test
  displayName: Test stage
  condition: or(eq(variables.isMain, 'True'), eq(variables.isRelease, 'True'), eq(variables.isProduction, 'True'))
  jobs:
  - job: Test
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.19.x'
    - script: |
        yarn install
        yarn test
      displayName: 'yarn install && test'



- stage: BuildApp
  displayName: build and push stage
  condition: or(eq(variables.isRelease, 'True'), eq(variables.isProduction, 'True'))
  jobs:
  - job: BuildPushImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'demo-azure-registry-connection1'
        repository: 'projectdemo'
        command: 'build'
        Dockerfile: '**/Dockerfile'
  
- stage: DevDeploy
  displayName: deploy development
  condition: eq(variables.isRelease, 'True')
  jobs:
    - job: Deploy
      steps:
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'NIH-Awd.OSU.NICHD.BMICloudComputing (336bf15c-53ea-4b44-9489-ca22bafe881b)'
          appType: 'webAppContainer'
          WebAppName: 'projdemo1'
          DockerNamespace: 'projectdemo'
          DockerRepository: 'projectdemo'
          DockerImageTag: '$(Build.BuildId)'
          StartupCommand: 'yarn start'

